---
title: "Presentation Ninja"
subtitle: "⚔<br/>with xaringan"
author: "Mengjun Chen"
institute: "RStudio"
date: "2022/9/28"
output:
  xaringan::moon_reader:
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

background-image: url(https://upload.wikimedia.org/wikipedia/commons/b/be/Sharingan_triple.svg)

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
```

???

Image credit: [Wikimedia Commons](https://commons.wikimedia.org/wiki/File:Sharingan_triple.svg)

---

# Experience R Code

```{r comment='#'}
dojutsu = c('地爆天星', '天照', '加具土命', '神威', '須佐能乎', '無限月読')
grep('天', dojutsu, value = TRUE)
```

---

# Experience R Tables

If you want to generate a table, make sure it is in the HTML format (instead of Markdown or other formats), e.g.,

```{r}
knitr::kable(head(iris), format = 'html')
```

---


# practice markdowns 

```markdown
  this is a markdown practice
```

---

# practice yaml


```yaml
  output:
    this is a practice using of yaml
```








